const products = [
    { id: 1, name: "Milk", x: 3, y: 0, price: 15 },
    { id: 2, name: "Bread", x: 4, y: 1, price: 10 },
    { id: 3, name: "Egg", x: 2, y: 2, price: 12 },
    { id: 4, name: "Onions", x: 4, y: 3, price: 20 },
    { id: 5, name: "Coke", x: 8, y: 4, price: 7 },
    { id: 6, name: "Chips", x: 2, y: 4, price: 5  },
    { id: 15, name: "Chicken", x: 4, y: 7, price: 25 },
    { id: 16, name: "Fish", x: 2, y: 7, price: 77 },
    { id: 7, name: "T Shirts", x: 6, y: 0, price: 80 },
    { id: 8, name: "Mundu", x: 5, y: 2, price: 50 },
    { id: 9, name: "Jeans", x: 3, y: 3, price: 150 },
    { id: 10, name: "Sweat shorts", x: 6, y: 6, price: 200 },
    { id: 11, name: "Jackets", x: 5, y: 4, price: 120  },
    { id: 12, name: "Scarves", x: 3, y: 5, price: 90  },
    { id: 17, name: "Surmai", x: 7, y: 7, price: 175  },
    { id: 18, name: "Tuna", x: 8, y: 7, price: 190  },
    { id: 14, name: "Pomfret", x: 5, y: 7, price: 250 },
];

const grids = [
    [
        {path: 1, is_start: 0},
        {path: 1, is_start: 0},
        {path: 1, is_start: 0},
        {path: 1, is_start: 0},
        {path: 1, is_start: 0},
        {path: 1, is_start: 0},
        {path: 1, is_start: 0},
        {path: 1, is_start: 0},
        {path: 1, is_start: 0},
        {path: 1, is_start: 0},
    ],
    [
        {path: 1, is_start: 0},
        {path: 0, is_start: 0},
        {path: 1, is_start: 0},
        {path: 0, is_start: 0},
        {path: 1, is_start: 0},
        {path: 0, is_start: 0},
        {path: 0, is_start: 0},
        {path: 1, is_start: 0},
        {path: 0, is_start: 0},
        {path: 0, is_start: 0},
    ],
    [
        {path: 0, is_start: 0},
        {path: 0, is_start: 0},
        {path: 1, is_start: 0},
        {path: 0, is_start: 0},
        {path: 1, is_start: 0},
        {path: 1, is_start: 0},
        {path: 0, is_start: 0},
        {path: 1, is_start: 0},
        {path: 1, is_start: 0},
        {path: 0, is_start: 0},
    ],
    [
        {path: 1, is_start: 0},
        {path: 0, is_start: 0},
        {path: 0, is_start: 0},
        {path: 1, is_start: 0},
        {path: 1, is_start: 0},
        {path: 0, is_start: 0},
        {path: 0, is_start: 0},
        {path: 1, is_start: 0},
        {path: 0, is_start: 0},
        {path: 0, is_start: 0},
    ],
    [
        {path: 1, is_start: 1},
        {path: 1, is_start: 0},
        {path: 1, is_start: 0},
        {path: 1, is_start: 0},
        {path: 1, is_start: 0},
        {path: 1, is_start: 0},
        {path: 0, is_start: 0},
        {path: 1, is_start: 0},
        {path: 1, is_start: 0},
        {path: 0, is_start: 0},
    ],
    [
        {path: 0, is_start: 0},
        {path: 1, is_start: 0},
        {path: 1, is_start: 0},
        {path: 1, is_start: 0},
        {path: 1, is_start: 0},
        {path: 0, is_start: 0},
        {path: 0, is_start: 0},
        {path: 1, is_start: 0},
        {path: 0, is_start: 0},
        {path: 0, is_start: 0},
    ],
    [
        {path: 0, is_start: 0},
        {path: 0, is_start: 0},
        {path: 1, is_start: 0},
        {path: 1, is_start: 0},
        {path: 1, is_start: 0},
        {path: 1, is_start: 0},
        {path: 1, is_start: 0},
        {path: 1, is_start: 0},
        {path: 1, is_start: 0},
        {path: 1, is_start: 0},
    ],
    [
        {path: 1, is_start: 0},
        {path: 1, is_start: 0},
        {path: 1, is_start: 0},
        {path: 1, is_start: 0},
        {path: 1, is_start: 0},
        {path: 1, is_start: 0},
        {path: 1, is_start: 0},
        {path: 1, is_start: 0},
        {path: 1, is_start: 0},
        {path: 1, is_start: 0},

    ]
];